# Generated by Django 5.2 on 2025-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=15)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nationality', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('emergency_contact_person', models.CharField(max_length=100)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
    ]
